### ISSUE TITLE
Staging deployment doesn’t work

### ISSUE THREAD

**Issue by strogonoff** [isogr/registry#11]
We have a new version of the site nearly ready, as part of the new build process:

<img width="1624" alt="Screenshot 2024-01-04 at 19 49 55" src="https://github.com/isogr/registry/assets/292959/e9b72840-ec6f-4a37-a0f9-8ae1fb60ac84">

I want to try this as staging build and it looks like staging build exists but it’s not configured properly. It uses the same `S3_BUCKET_NAME` as production, for example. Can we provide the infra for staging build at isogr-staging.demo.paneron.org? cc @kwkwan

**Comment by strogonoff** [comment]
We can also switch to GH pages for this. Currently, this repo uses S3.

**Comment by ronaldtse** [comment]
@kwkwan please help facilitate and move this to GH Pages as soon as possible. Thanks.

**Comment by kwkwan** [comment]
@strogonoff The names of the environment variables such as `CLOUDFRONT_DISTRIBUTION_ID` and `S3_BUCKET_NAME` can be the same because they are specified in different environments (`staging` and `production`) with different values.

**Comment by kwkwan** [comment]
The site is still deployed to S3 at this moment as `yarn build` cannot be run successfully.  Once the build runs successfully, it will be moved to Github Pages.  However, the staging site will be removed as one repo can only serve one site in Github Pages.

**Comment by strogonoff** [comment]
If we can’t make staging work then there should be staging workflow. Having broken workflows is not a good idea.

**Comment by ronaldtse** [comment]
One repo can only serve one GH Pages site. This means we can duplicate the repo for staging if there is a need for staging.

Since there is currently no "production" site, we don't need a separate "staging" site for now.

@strogonoff can you provide instructions on how to build this site with the new code?

**Comment by strogonoff** [comment]
@ronaldtse 

I don’t think we must fix the build before migration, Github pages build can be initially failing like any other build :)

Regardless, I’ll update the main deployment GHA workflow. All I need is just to be sure that repo settings are correct. I don’t see the settings and I don’t want to be wondering whether something is wrong with the workflow or the repo is simply not configured correctly in settings.

**Comment by strogonoff** [comment]
This issue is about staging deployment, we have no staging so the issue is fixed.

**Comment by ronaldtse** [comment]
@strogonoff the only setting to be made correct is presence of the custom domain.

@kwkwan can you please help set the custom domain? Thanks.
