### ISSUE TITLE
Deploy under geodetic-v2.isotc211.org domain

### ISSUE THREAD

**Issue by strogonoff** [isogr/registry#20]
More: https://github.com/isogr/register-system-transition/issues/17

**Comment by kwkwan** [comment]
Refer to: https://github.com/paneron/infrastructure/issues/34 and https://github.com/ISO-TC211/infrastructure/issues/14.

**Comment by ronaldtse** [comment]
@strogonoff we also hold isogr.org which we could potentially use.

**Comment by strogonoff** [comment]
I believe this one is done, geodetic-v2 is working. We will check with Mike if we should move it to isogr.org on the upcoming CB meeting.
