### ISSUE TITLE
Implement staging build

### ISSUE THREAD

**Issue by strogonoff** [isogr/registry#22]
There will almost certainly be renewed interest in a “staging”/proposal review deployment after the upcoming meeting. We already know that it will be desirable to share proposed register with certain people in control body in read-only mode.

I think staging is ill-suited for GitHub Pages, because it would likely need at least basic HTTP authentication (as it would contain pending proposals in its dataset, for example). 
(In future we may also want to deploy multiple stagings for different proposals, but that can be considered in a few months.)

cc @ribose-jeffreylau @kwkwan What could be good options to handle deploying this extra site? AWS? This is not urgent, but it’ll very likely be mentioned on the meeting.

Currently there’s a staging branch, but AWS deployment fails (because we moved to GHP, I guess).

**Comment by ribose-jeffreylau** [comment]
A staging instance is now a requirement.

@strogonoff Are the security requirements for the staging instance still the same?

**Comment by strogonoff** [comment]
I am pretty sure we just need a duplicate instance, connected to either a branch in the repo or a separate repo, and that’s all… @ribose-jeffreylau

**Comment by ronaldtse** [comment]
It's easy to make a mirror repo using GitHub Actions.

**Comment by ribose-jeffreylau** [comment]
Staging repo has been initialized: https://github.com/isogr/registry-staging

Mirroring GitHub Action has been tested.

Remaining issues:

- https://github.com/isogr/registry-staging/issues/1
- https://github.com/isogr/registry-staging/issues/2

**Comment by strogonoff** [comment]
@ribose-jeffreylau if necessary to bump site-builder workflow for staging, now it’s done in https://github.com/isogr/registry-staging/tree/staging/.github/workflows, right? Which workflow is responsible for publishing the staging, deploy-staging or deploy-master? Which one is unnecessary?

Same question for this repo, do we remove one of the workflows since staging is now in a distinct repo?

**Comment by ribose-jeffreylau** [comment]
@strogonoff Assuming all changes flow from `master` branch of 'registry' repo to `staging` branch of 'registry', then to `staging` branch of 'registry-staging' repo, no workflows are unnecessary.

**deploy-staging** workflow is responsible for deploying `staging` branch of 'registry-staging', while **deploy-master** is for deploying `master` branch of 'registry'.
**mirror-staging** is responsible for pushing changes from `staging` branch of 'registry' to 'registry-staging'.

So, we only modify workflow files from this repo, 'registry'.  Any changes done to its `staging` will be propagated to 'registry-staging' via GHA.

**Comment by ribose-jeffreylau** [comment]
I think this is done.
